events {}

http {
  server {
    listen 80;
    server_name wifi-dashboard.sagem;

    # Redirect all HTTP to HTTPS
    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;
    server_name wifi-dashboard.sagem;

    ssl_certificate     /etc/nginx/certs/cert.pem;
    ssl_certificate_key /etc/nginx/certs/key.pem;

    # Forward all requests to Next.js
    location / {
      proxy_pass         http://web:3000;
      proxy_http_version 1.1;
      proxy_set_header   Upgrade $http_upgrade;
      proxy_set_header   Connection 'upgrade';
      proxy_set_header   Host $host;
      proxy_cache_bypass $http_upgrade;
    }
  }
}